### ISSUE TITLE
Not entering the WAIT_CONFIG_ACK

### ISSUE THREAD

**Issue by vallettea** [lab11/iM880-serial-comm#4]
Hello,
thanks a lot for sharing this work as I was going to have to do it all by myself.
I'm trying to run it with a iM880B-L chip but nothing outputs on the command line.
After some time I figured that the chip is responding but not entering WAIT_CONFIG_ACK.
I guess it is because I have something wrong in `config_msg`, and in fact I don't know what I should put in the variables `DEVICE_ID` and `DEVICE_GROUP` ?

Where can i find these information ? Is it related to the chip EUI ? If so how can i get the device EUI ?

thanks a lot

**Comment by adkinsjd** [comment]
DEVICE_ID and DEVICE_GROUP are arbitrary fields. The base software from IMST filters all packets not from the same DEVICE_GROUP and DEVICE_ID can be used to send packets to a specific device. I don't believe that these settings could be causing the issue that you are describing, but the HCI layer specification certainly could have changed since we last used this library.

I am too busy to look into your deeper issue right now, but I am happy to look for a solution after my deadlines have passed in late April/early May. We will also accept a pull request if you solve the problem first!

**Comment by vallettea** [comment]
ok thanks.
I'll dig into this and see what I can do.

**Comment by adkinsjd** [comment]
Did you figure out the cause of your problem? If not, can you send me the firmware version that you are running on the iM880 so that I can attempt to replicate the issue?

**Comment by vallettea** [comment]
thanks fo r the enquiry. I had to code something else since i was using the chip in lorawan mode
